import { useConfirm } from '@/hooks/useConfirm'
import { Button } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

const Home: NextPage = () => {
  const confirm = useConfirm()

  const handleClick = () => {
    confirm({
      title: 'Xoá',
      description: <div>sẽ bị xoá !!!</div>,
      onConfirm: async () => {
        await sleep(3000)
        console.log('done')
      }
    })
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button onClick={handleClick}>Click</Button>
    </div>
  )
}

export default Home
