import { useConfirm } from '@/hooks/useConfirm'
import { Button, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import ConfirmDelete from '@/components/shared/DialogHeader/ConfirmDelete'
import Link from 'next/link'
import { sleep } from '@/utils/sleep'

const Home: NextPage = () => {
  const confirm = useConfirm()

  const handleClick = () => {
    confirm({
      title: <ConfirmDelete>Are you sure you want to?</ConfirmDelete>,
      description: <strong>sẽ bị xoá !!!</strong>,
      onConfirm: async () => {
        await sleep(3000)
        console.log('done')
      },
    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button onClick={handleClick}>number from server</Button>

      <Typography>
        <Link href={'/404'}>c</Link>
      </Typography>
    </div>
  )
}

export default Home
